### ISSUE TITLE
Pushkit token not getting in some devices iOS

### ISSUE THREAD

**Issue by mssdilipkumar** [hasyapanchasara/PushKit_SilentPushNotification#3]
I am using same certificates and Diawi Build for all devices.
I am able to get `didUpdatePushCredentials` device token. working in --> iPhone 5s , iPhone6 Plus

`didUpdatePushCredentials` Not working in --> iPhone6 and iPhone7

iOS version is same in devices 10.3.2

`didUpdatePushCredentials` delegate is working in development mode and ad-hoc mode both.

it is not a certificate or delegate issue.

i have tried all ways that is suggested by StackOverflow Members
-->. https://stackoverflow.com/q/45054269/4970453

please Reply

**Comment by hasyapanchasara** [comment]
Hello,

Your issue is been trouble shoot with many ways and resolved now.

https://stackoverflow.com/questions/45054269/pushkit-token-not-getting-in-some-devices-ios/45058640#45058640

Options
(1) Make build with diawi.com , install in device, once you have device token, just show it in alert view controller
(2) Also keep distribution certificates, Pushkit does not work in development.
(3) Change com identifier and try again
(4) Keep puhkit code in app delegate

Good luck.
